---
name: workflow
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.3
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' }}
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python3 -m pip install build
    - run: python3 -m build
    - uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
